name: DB

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: '3307' # optional, default is 3306
        container port: '3307' # optional, default is 3306
        mysql root password: 'password' # optional, default is 
        mysql database: 'daplex' # optional, default is 
        mysql user: 'root' # optional, default is 
        mysql password: 'password' # optional, default is 
        
        
